version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./conf.d:/etc/nginx/conf.d:cached
    depends_on:
      - php
      - mysql
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - app_network

  mysql:
    platform: linux/x86_64
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3006
    environment:
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  db:

networks:
  app_network:
